spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eStudy?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB